import * as d from "./components";

export const DIRECTIVES = [
    d.MwAppBar,
    d.MwAppBarTitle,
    d.MwAvatar,
    d.MwButton,
    d.MwCard,
    d.MwCardBody,
    d.MwCardFooter,
    d.MwCardHeader,
    d.MwCardImage,
    d.MwCardTitle,
    d.MwCheckbox,
    d.MwChip,
    d.MwDivider,
    d.MwIcon,
    d.MwIconGallery,
    d.MwLink,
    d.MwMenu,
    d.MwMenuItem,
    d.MwMenuList,
    d.MwPopover,
    d.MwRadio,
    d.MwSlider,
    d.MwSwitch,
    d.MwTab,
    d.MwTabs,
    d.MwTextfield,
];
