/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
export namespace Components {
  interface MyComponent {
    /**
     * The first name
     */
    first: string;
    /**
     * The last name
     */
    last: string;
    /**
     * The middle name
     */
    middle: string;
  }
  interface TlmButton {
    /**
     * Unique id for each tlm-button.
     */
    buttonId: string;
  }
}
declare global {
  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };
  interface HTMLTlmButtonElement extends Components.TlmButton, HTMLStencilElement {}
  var HTMLTlmButtonElement: {
    prototype: HTMLTlmButtonElement;
    new (): HTMLTlmButtonElement;
  };
  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'tlm-button': HTMLTlmButtonElement;
  }
}
declare namespace LocalJSX {
  interface MyComponent {
    /**
     * The first name
     */
    first?: string;
    /**
     * The last name
     */
    last?: string;
    /**
     * The middle name
     */
    middle?: string;
  }
  interface TlmButton {
    /**
     * Unique id for each tlm-button.
     */
    buttonId: string;
  }
  interface IntrinsicElements {
    'my-component': MyComponent;
    'tlm-button': TlmButton;
  }
}
export { LocalJSX as JSX };
declare module '@stencil/core' {
  export namespace JSX {
    interface IntrinsicElements {
      'my-component': LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
      'tlm-button': LocalJSX.TlmButton & JSXBase.HTMLAttributes<HTMLTlmButtonElement>;
    }
  }
}
