name: Development Build and Deploy
on:
  push:
    branches: [dev]
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3

      # https://github.com/actions/checkout#push-a-commit-using-the-built-in-token
      - name: Set GitHub Actions as Commit Author
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Build
        run: |
          npm ci
          npm run build-tokens
          npm run build-stencil
          npm run build-storybook

      - name: Checkout Dev Target
        uses: actions/checkout@v3
        with:
          repository: maibornwolff/mwui-dev
          path: "deploy"
          token: ${{ secrets.PAT }}

      - name: Push files to target
        run: |
          cp -r docs/* docs
          cd docs
          git add .
          git commit -m $GITHUB_SHA
          git push
