# builds tokens, stencil and storybook. Will be published via pages in mwui-dev repository
name: Release - Update Tokens and Build WebComponents
on:
    push:
        tags:
            - "v[0-9]+.[0-9]+.[0-9]+"
permissions:
    contents: write
jobs:
    transformTokens:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: "npm"
                  cache-dependency-path: "**/package-lock.json"

            - name: Install dependencies
              run: npm ci

            - name: Transform Figma Tokens & Style Dictionary
              run: npm run build-tokens

            - name: Run lint on Stencil components
              run: npm run lint

            - name: Run Stencil unit tests
              run: npm run test:spec

            - name: Build Stencil
              run: npm run build-stencil

            - name: Generate Storybook
              run: npm run build-storybook

            # Committing the build will trigger the Pages Action for release build of SB
            - uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  token: ${{ secrets.PAT }}
                  commit_message: ${{ github.event.head_commit.message }}
                  branch: main
