name: Build and Publish storybook to GitHub Pages

on:
    workflow_dispatch:
        inputs:
            tag:
                description: "New tag name"
                required: true
jobs:
    deploy:
        permissions:
          contents: 'read'
          id-token: 'write'
        environment:
            name: github-pages
            url: ${{ steps.build-publish.outputs.page_url }}
        runs-on: ubuntu-latest
        steps:
            - id: build-publish
              uses: bitovi/github-actions-react-to-ghp@v1.2.0
              with:
                  path: docs
                  build_command: npm run build-tokens && npm run build-stencil && npm run build-storybook
